In [1]:
import findspark
findspark.init()
import shapely
import pandas as pd
import geopandas as gpd
from pyspark.sql import SparkSession
from pyspark import SparkContext
from pyspark import SparkConf
from sedona.register import SedonaRegistrator
from sedona.utils import SedonaKryoRegistrator, KryoSerializer

In [2]:

spark = SparkSession. \
builder. \
appName('appName'). \
config("spark.serializer", KryoSerializer.getName). \
config("spark.executor.memory", "5g"). \
config("spark.driver.memory", "10g"). \
config('spark.driver.maxResultSize', '5g'). \
config("spark.kryo.registrator", SedonaKryoRegistrator.getName). \
config('spark.jars.packages',
           'org.apache.sedona:sedona-python-adapter-3.0_2.12:1.2.0-incubating,org.datasyslab:geotools-wrapper:1.1.0-25.2'). \
getOrCreate()
SedonaRegistrator.registerAll(spark)

True

In [3]:

import time

# start_time = time.time()

# path_scince = "../SCINCE 2020/"
# # Estados_SCINCE = ['01_AGS','02_BC','03_BCS','04_CAMP','05_COAH','06_COL','07_CHIS','08_CHIH','09_CDMX','10_DGO','11_GTO','12_GRO','13_HGO','14_JAL','15_MEX','16_MICH','17_MOR','18_NAY','19_NL','20_OAX','21_PUE','22_QRO','23_Q_ROO','24_SLP','25_SIN','26_SON','27_TAB','28_TAMS','29_TLAX','30_VER','31_YUC','32_ZAC']
# Estados_SCINCE = ['19_NL']

# for estado in Estados_SCINCE:
#     tabla_principal_poblacion = f"../SCINCE 2020/{estado}/cartografia/manzana.shp"

#     TPP = gpd.read_file(tabla_principal_poblacion)
#     print(f"Procesando el estado: {estado}")

#     Pandas_TPP = pd.DataFrame(TPP)

In [4]:
# Pandas_TPP.to_csv('Pandas_TPP.csv', index = False)

In [5]:
# pip install pandas==1.2.5

In [7]:
Pandas_TPP

,CVEGEO,POB1,POB2,POB2_R,POB4,POB4_R,POB5,POB5_R,POB6,POB6_R,...,POB121,POB121_R,POB122,POB122_R,POB123,POB123_R,POB124,POB124_R,OID,geometry
0,1900100010055001,10.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,...,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,1,POLYGON ((2660708.778099999 1544166.7115000002...
1,1900100010036022,7.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,...,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,2,"POLYGON ((2660051.3279 1544688.1697000004, 266..."
2,1900100010036021,30.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-6.0,-6.0,3,POLYGON ((2660029.604000002 1544696.3304000013...
3,1900100010036019,5.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,...,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,4,"POLYGON ((2660117.3794 1544712.8128000014, 266..."
4,1900100010036007,0.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,...,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,5,POLYGON ((2660489.9975999966 1544597.515099998...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76990,1905000010469800,2.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,...,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,76991,MULTIPOLYGON (((2700831.9913000017 1622314.393...
76991,1905000010473800,0.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,...,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,76992,POLYGON ((2699535.081699997 1625591.1009000018...
76992,1905100010146800,11.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,...,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,76993,POLYGON ((2656147.1860999987 1606640.252300001...
76993,190510001017A800,0.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,...,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,-8.0,76994,MULTIPOLYGON (((2656162.034900002 1603167.0425...
76994,190510001024A800,3.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,...,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,-6.0,76995,POLYGON ((2656655.0155000016 1606372.493900001...

In [8]:
Spark_TPP = spark.createDataFrame(Pandas_TPP)

KeyboardInterrupt:

In [ ]:
df = None
estado = '19_NL'
for tabla_sec in tablas_secundarias:
    tabla_secundaria = f"../SCINCE 2020/{estado}/tablas/cpv2020_manzana_{tabla_sec}.dbf"
    SEC = gpd.read_file(tabla_secundaria)
    print(f"Procesando...: {estado}")

    Pandas_SEC = pd.DataFrame(SEC).drop(['geometry'], axis=1)
    Spark_SEC = spark.createDataFrame(Pandas_SEC)
    if df is None:
        df = Spark_TPP.join(Spark_SEC, on=['CVEGEO'], how='inner')
    else:
        df = df.join(Spark_SEC, on=['CVEGEO'], how='inner')

print(f"Guardando el estado: {estado}")
df.write.parquet(f"../SCINCE_Parquets/{estado}.parquet")
print(f"Concluido estado: {estado}")
    
print("--- %s segundos ---" % (time.time() - start_time))

In [ ]:
hex = f"../Mex-Hex-5k/Mex-Hex-5k.shp"
TH = gpd.read_file(hex)
Pandas_TH = pd.DataFrame(TH)
Spark_TH = spark.createDataFrame(Pandas_TH)
Spark_TH.write.parquet(f"../HEX_Parquets/Mex-Hex-5k.parquet")

In [ ]:
start_time = time.time()

HX = gpd.read_file("../Mex-Hex-5k/Mex-Hex-5k.shp")

Estados_DENUE = ["19"]
for estado in Estados_DENUE:
    
    print(f"Procesando el estado: {estado}")
    if estado in ["15_1","15_2"] :
        tabla_denue = f"..conjunto_de_datos/denue_inegi_{estado}.shp"
    else:
        tabla_denue = f"../conjunto_de_datos/denue_inegi_{estado}_.shp"
    
    TD = gpd.read_file(tabla_denue)
    TD = TD.set_crs('epsg:4326', allow_override=True)
    TD["raz_social"] = TD["raz_social"].astype(str)

    Spark_TD = spark.createDataFrame(TD.to_crs(HX.crs))
    
    print(f"Guardando el estado: {estado}")
    Spark_TD.write.parquet(f"../DENUE_Parquets/{estado}.parquet")
    print(f"Concluido estado: {estado}")

In [ ]:
#DENUE: https://drive.google.com/file/d/1CbCm0n41uKHPi-L8bTag2G6RA71tdaM4/view?usp=sharing
!gdown 1CbCm0n41uKHPi-L8bTag2G6RA71tdaM4